version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    depends_on:
      - main-db
      - travelschedule-db
      - booking-db
      - travelhistory-db
      - refundrequest-db
      - recommendation-db

  main-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - main-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  travelschedule-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: travelschedule_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - travelschedule-db-data:/var/lib/postgresql/data

  booking-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - booking-db-data:/var/lib/postgresql/data

  travelhistory-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: travelhistory_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - travelhistory-db-data:/var/lib/postgresql/data

  refundrequest-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: refundrequest_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - refundrequest-db-data:/var/lib/postgresql/data

  recommendation-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: recommendation_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - recommendation-db-data:/var/lib/postgresql/data

volumes:
  main-db-data:
  travelschedule-db-data:
  booking-db-data:
  travelhistory-db-data:
  refundrequest-db-data:
  recommendation-db-data:
